#!/bin/bash
#
# CREATED USING THE BIOHPC PORTAL on Fri Apr 22 2022 13:12:43 GMT-0500 (Central Daylight Time)
#
# This file is batch script used to run commands on the BioHPC cluster.
# The script is submitted to the cluster using the SLURM `sbatch` command.
# Lines starting with # are comments, and will not be run.
# Lines starting with #SBATCH specify options for the scheduler.
# Lines that do not start with # or #SBATCH are commands that will run.

# Name for the job that will be visible in the job queue and accounting tools.
#SBATCH --job-name Trimm

# Name of the SLURM partition that this job should run on.
#SBATCH -p 256GB       # partition (queue)
# Number of nodes required to run this job
#SBATCH -N 1

# Memory (RAM) requirement/limit in MB.
#SBATCH --mem 252928      # Memory Requirement (MB)

# Time limit for the job in the format Days-H:M:S
# A job that reaches its time limit will be cancelled.
# Specify an accurate time limit for efficient scheduling so your job runs promptly.
#SBATCH -t 2-0:0:00

# The standard output and errors from commands will be written to these files.
# %j in the filename will be replace with the job number when it is submitted.
#SBATCH -o Trimm_%j.out
#SBATCH -e Trimm_%j.err

# Send an email when the job status changes, to the specfied address.
#SBATCH --mail-type ALL
#SBATCH --mail-user David.Atkinson2@UTsouthwestern.edu

# module load Trimmomatic/0.32

# COMMAND GROUP 1
FQDIR='/work/Neuroinformatics_Core/s213872/Neurocore/VIKRAM/01_FASTQ'
WORKDIR='/work/Neuroinformatics_Core/s213872'

##=================================================##
## TRIMMOMATIC ##
##=================================================##
date
echo "================> Running TRIMMOMATIC"

cd ${FQDIR}

cat samples.txt | while read line
do
 echo "Processing" ${line}
 fq1=`echo ${line}"_R1_001.fastq.gz"`
 fq2=`echo ${line}"_R2_001.fastq.gz"`
 echo ${fq1} "|" ${fq2}
 
 cat ${line}"_R1_001_fastqc/fastqc_data.txt" | grep Over -A 100 | grep 'Illumina\|TruSeq' | grep -P '^[A-Z]' | nl | awk '{print ">" $1 "_adapter\n" $2}' > ${line}"_R1_adapters.fa"
 cat ${line}"_R2_001_fastqc/fastqc_data.txt" | grep Over -A 100 | grep 'Illumina\|TruSeq' | grep -P '^[A-Z]' | nl | awk '{print ">" $1 "_adapter\n" $2}' > ${line}"_R2_adapters.fa"
 cat ${line}"_R1_adapters.fa" ${line}"_R2_adapters.fa" > ${line}"_adapters.fa"
 rm ${line}"_R1_adapters.fa"
 rm ${line}"_R2_adapters.fa"
 
 paired1=`basename ${fq1} | sed -e "s/.fastq.gz/.NoAdapt.Trim.fastq.gz/"`
 paired2=`basename ${fq2} | sed -e "s/.fastq.gz/.NoAdapt.Trim.fastq.gz/"`
 unpaired1=`basename ${fq1} | sed -e "s/.fastq.gz/.Unp.NoAdapt.Trim.fastq.gz/"`
 unpaired2=`basename ${fq2} | sed -e "s/.fastq.gz/.Unp.NoAdapt.Trim.fastq.gz/"`
 echo $paired1 "|" $paired2
 echo $unpaired1 "|" $unpaired2
 
java -jar /endosome/work/Neuroinformatics_Core/s213872/RESOURCES/Trimmomatic-0.35/trimmomatic-0.35.jar PE -phred33 $fq1 $fq2 "$paired1" "$unpaired1" "$paired2" "$unpaired2" ILLUMINACLIP:${line}"_adapters.fa":2:30:10 -threads 24 SLIDINGWINDOW:4:18 LEADING:7 TRAILING:7 MINLEN:35
 echo "---------------------------------->"
done

cd ${WORKDIR}

echo "================> Finished TRIMMOMATIC"
date